---
- name: Install Main Packages
  become: true
  apt:
    state: present
    pkg:
    - apt-transport-https
    - python3-debian # required for ansible deb822_repository module
    - ca-certificates # required for verifying PPAs
